services:
  zookeeper:
    image: bitnami/zookeeper:3.9
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.7
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  flink-jobmanager:
    image: flink:1.17.2-scala_2.12-java11
    environment:
      JOB_MANAGER_RPC_ADDRESS: flink-jobmanager
      FLINK_PROPERTIES: |
        taskmanager.numberOfTaskSlots: 2
        containerized.master.env.JAVA_TOOL_OPTIONS: --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED
        containerized.taskmanager.env.JAVA_TOOL_OPTIONS: --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      - flink_data:/opt/flink/usrlib

  flink-taskmanager:
    image: flink:1.17.2-scala_2.12-java11
    depends_on:
      - flink-jobmanager
    command: taskmanager
    environment:
      JOB_MANAGER_RPC_ADDRESS: flink-jobmanager
      FLINK_PROPERTIES: |
        taskmanager.numberOfTaskSlots: 2
        containerized.master.env.JAVA_TOOL_OPTIONS: --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED
        containerized.taskmanager.env.JAVA_TOOL_OPTIONS: --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED
    deploy:
      replicas: 1
    volumes:
      - flink_data:/opt/flink/usrlib

  submit:
    build: .
    image: flink-kafka-mongo:latest
    depends_on:
      - kafka
      - mongo
      - flink-jobmanager
      - flink-taskmanager
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
      KAFKA_TOPIC: events
      KAFKA_GROUP_ID: flink-mongo-consumer
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB: flinkdb
      MONGO_COLLECTION: events
      JAVA_TOOL_OPTIONS: --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED
    volumes:
      - flink_data:/opt/flink/usrlib
    entrypoint: ["bash", "-lc", "./bin/flink run -d -m http://flink-jobmanager:8081 /opt/flink/usrlib/app.jar"]
    
volumes:
  mongo_data: {}
  flink_data: {}


